In [1]:
import numpy as np

In [2]:
%pip install numpy

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.7 MB 4.9 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.7 MB 5.5 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.7 MB 5.7 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.7 MB 5.8 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.7 MB 6.0 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.7 MB 6.0 MB/s eta 0:00:01
   ---------------------------- ----------- 9.2/12.7 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.7 MB 6.2 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.7 MB 6.2 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 6.0 MB/s  0:00:02
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np


In [3]:

print(np.__version__)

2.5.3


In [4]:
A = np.array([10,20,30,40])

In [5]:
#indexing
A[2]

np.int64(30)

In [6]:
A[0]

np.int64(10)

In [7]:
#slicing
A[:2]

array([10, 20])

In [8]:
A[0] = 2#it is int
A

array([ 2, 20, 30, 40])

In [9]:
A[0] = 'pune'

ValueError: invalid literal for int() with base 10: 'pune'

In [10]:
A[0] = 'A'

ValueError: invalid literal for int() with base 10: 'A'

In [12]:
A[0] = 1.222
A

array([ 1, 20, 30, 40])

In [5]:
A[0] = True
A

array([ 1, 20, 30, 40])

In [13]:
#iterable
for i in A:
    print(i)

1
20
30
40


In [14]:
#funtions
A.sum()

np.int64(91)

In [15]:
A.min()

np.int64(1)

In [16]:
A.max()

np.int64(40)

In [17]:
#diffrent ways to create numpy array
A = np.array([12,20])

In [20]:
B = np.arange(10,20,2) #exclusive
B#start from 10 end at before 20 and increment by 2

array([10, 12, 14, 16, 18])

In [21]:
C = np.linspace(0,1,5)#inclusive
C #start at 0 and end at 1 and increment at 5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
C = np.linspace(0,10,3)
C

array([ 0.,  5., 10.])

In [25]:
C = np.linspace(3,15,5)
C #take starting and end at this and makes the parts at the last 5

array([ 3.,  6.,  9., 12., 15.])

In [6]:
A.std()

np.float64(14.411367041332339)

In [7]:
np.random.randint(0,100,10)

array([60, 72, 90, 41, 47, 60,  6, 97, 15, 18], dtype=int32)

In [8]:
np.random.seed(7)
np.random.randint(0,100,10)

array([47, 68, 25, 67, 83, 23, 92, 57, 14, 23], dtype=int32)

In [3]:
A = np.array([[10,20,30],[40,50,60]])

In [4]:
print(A)

[[10 20 30]
 [40 50 60]]


In [5]:
A

array([[10, 20, 30],
       [40, 50, 60]])

In [7]:
print(A[0][2])

30


In [8]:
A[-1][-1]

np.int64(60)

In [9]:
print(A[0,2])

30


### Properties 

In [10]:
A.dtype #tells the which type of data

dtype('int64')

In [11]:
print(A.dtype)

int64


In [12]:
A.ndim #tells the how much dimentions code

2

In [13]:
A.size #tells the number of element

6

In [14]:
A.shape #give value in tuple (row,column)

(2, 3)

##### Reshape 

In [15]:
A = np.array([10, 12, 14, 16, 18])

In [16]:
print(A.ndim)
print(A.size)
print(A.shape)

1
5
(5,)


In [17]:
B = A.reshape(3,2)
B

ValueError: cannot reshape array of size 5 into shape (3,2)

In [18]:
A = np.array([10, 12, 14, 16, 18,20])
print(A.ndim)
print(A.size)
print(A.shape)

1
6
(6,)


In [19]:
B = A.reshape(3,2)
B

array([[10, 12],
       [14, 16],
       [18, 20]])

In [21]:
print(B.ndim)
print(B.size)
print(B.shape)

2
6
(3, 2)


In [22]:
c = A.reshape(2,3)
c

array([[10, 12, 14],
       [16, 18, 20]])

In [23]:
d = A.reshape(6,1)
d

array([[10],
       [12],
       [14],
       [16],
       [18],
       [20]])

In [24]:
e = A.reshape(1,6)
e

array([[10, 12, 14, 16, 18, 20]])

In [2]:
np.random.seed(49)
marks = np.random.randint(0,100,(6,4))

In [3]:
marks

array([[42, 45, 40, 54],
       [12, 69,  5, 49],
       [18, 36, 12, 96],
       [82, 99, 26,  6],
       [59, 33, 70, 15],
       [92, 79, 72, 99]], dtype=int32)

In [4]:
#topper marks in every subject?
print(marks.max(axis = 0))

[92 99 72 99]


In [5]:
#what is avg marks of topper?
print(marks.mean(axis = 0).max())

60.166666666666664


In [6]:
#addition of each row
print(marks.sum(axis = 1))

[181 135 162 213 177 342]


In [7]:
#avg marks of each subject
print(marks.mean(axis = 0))

[50.83333333 60.16666667 37.5        53.16666667]


#### Operators Bitwise

In [15]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])

### Array to Array

In [16]:
A+B

array([11, 22, 33, 44])

In [17]:
A < B

array([False, False, False, False])

### Array to sacaler values

In [18]:
print(A + 5) #gives each value to array elemnet and add

[15 25 35 45]


In [20]:
print(A*5)
print(A//2)

[ 50 100 150 200]
[ 5 10 15 20]


In [25]:
A < 20

array([ True, False, False, False])

In [28]:
np.random.seed(49)
A = np.random.randint(0,100,20)
A

array([42, 45, 40, 54, 12, 69,  5, 49, 18, 36, 12, 96, 82, 99, 26,  6, 59,
       33, 70, 15], dtype=int32)

In [29]:
A<50

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True, False, False, False,  True,  True, False,  True,
       False,  True])

In [31]:
print(sum(A<50)) # it gives count

13


In [33]:
#even numbers count
print(A % 2 == 0)
print(sum(A % 2 == 0))

[ True False  True  True  True False False False  True  True  True  True
  True False  True  True False False  True False]
12


In [34]:
b1 = A < 30
b2 = A > 60


In [35]:
b1

array([False, False, False, False,  True, False,  True, False,  True,
       False,  True, False, False, False,  True,  True, False, False,
       False,  True])

In [36]:
b2

array([False, False, False, False, False,  True, False, False, False,
       False, False,  True,  True,  True, False, False, False, False,
        True, False])

In [37]:
#here we don't do by the 'and' we have to use the '&' and same like the 'or' we use '|'
b1 & b2

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [38]:
sum(b1 & b2)

np.int64(0)

In [39]:
b1 | b2

array([False, False, False, False,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True])

In [40]:
sum(b1 | b2)

np.int64(12)

In [41]:
A

array([42, 45, 40, 54, 12, 69,  5, 49, 18, 36, 12, 96, 82, 99, 26,  6, 59,
       33, 70, 15], dtype=int32)

In [45]:
A > 50

array([False, False, False,  True, False,  True, False, False, False,
       False, False,  True,  True,  True, False, False,  True, False,
        True, False])

In [46]:
A % 2 == 0

array([ True, False,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True, False,  True,  True, False, False,
        True, False])

In [47]:
(A > 50) & (A % 2== 0)

array([False, False, False,  True, False, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
        True, False])

In [48]:
sum((A > 50) & (A % 2== 0))

np.int64(4)

## Filtering

In [53]:
A[A > 50]

array([54, 69, 96, 82, 99, 59, 70], dtype=int32)

In [54]:
#even numbers from array A
A[A % 2 == 0]

array([42, 40, 54, 12, 18, 36, 12, 96, 82, 26,  6, 70], dtype=int32)

In [59]:
#failed students topper (fail < 40)
A[A < 40]

array([12,  5, 18, 36, 12, 26,  6, 33, 15], dtype=int32)

In [60]:
A[A < 40].max()

np.int32(36)

In [61]:
#what is the sum of elements div by 5
A[A % 5 == 0].sum()

np.int64(175)

In [63]:
A.mean()

np.float64(43.4)

In [62]:
# print students who got more than average marks of all
A[A > A.mean()]

array([45, 54, 69, 49, 96, 82, 99, 59, 70], dtype=int32)

In [65]:
#extra-ordinary students total who has marks > 90 and marks < 10 
sum((A > 90) | (A <10))

np.int64(4)

In [67]:
A

array([42, 45, 40, 54, 12, 69,  5, 49, 18, 36, 12, 96, 82, 99, 26,  6, 59,
       33, 70, 15], dtype=int32)

In [68]:
#give Grace marks to the failed students of 10 and pass to 5
np.where(A<40,A + 10,A+5)

array([ 47,  50,  45,  59,  22,  74,  15,  54,  28,  46,  22, 101,  87,
       104,  36,  16,  64,  43,  75,  25], dtype=int32)

In [70]:
#garce marks to failed students of 10
np.where(A<40,A + 10,A)

array([42, 45, 40, 54, 22, 69, 15, 49, 28, 46, 22, 96, 82, 99, 36, 16, 59,
       43, 70, 25], dtype=int32)

In [71]:
#Make 0 to failed students and 1 to pass
np.where(A<40,0,1)

array([1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0])

In [17]:
np.random.seed(49)
B = np.random.randint(0,100,(6,4))
B

array([[42, 45, 40, 54],
       [12, 69,  5, 49],
       [18, 36, 12, 96],
       [82, 99, 26,  6],
       [59, 33, 70, 15],
       [92, 79, 72, 99]], dtype=int32)

In [18]:
B[3,1]

np.int32(99)

In [21]:
B[-3:,-2:]
    

array([[26,  6],
       [70, 15],
       [72, 99]], dtype=int32)

In [73]:
pip install scikit-learn

   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.4 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.4 MB 2.0 MB/s eta 0:00:04
   ------ --------------------------------- 1.3/8.4 MB 2.3 MB/s eta 0:00:04
   ------- -------------------------------- 1.6/8.4 MB 2.2 MB/s eta 0:00:04
   -------- ------------------------------- 1.8/8.4 MB 2.2 MB/s eta 0:00:04
   ---------- ----------------------------- 2.1/8.4 MB 1.7 MB/s eta 0:00:04
   ---------- ----------------------------- 2.1/8.4 MB 1.7 MB/s eta 0:00:04
   ----------- ---------------------------- 2.4/8.4 MB 1.5 MB/s eta 0:00:04
   --------------- ------------------------ 3.1/8.4 MB 1.7 MB/s eta 0:00:04
   ---------------- ----------------------- 3.4/8.4 MB 1.7 MB/s eta 0:00:03
   ------------------ --------------------- 3.9/8.4 MB 1.7 MB/s eta 0:00:03
   -------------------- ------------------- 4.2/8.4 MB 1.8 MB/s eta 0:00:03
   ---------------------- 

In [74]:
import skimage.io as io

ModuleNotFoundError: No module named 'skimage'