In [2]:
import numpy as np

In [2]:
%pip install numpy

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.7 MB 4.9 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.7 MB 5.5 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.7 MB 5.7 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.7 MB 5.8 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.7 MB 6.0 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.7 MB 6.0 MB/s eta 0:00:01
   ---------------------------- ----------- 9.2/12.7 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.7 MB 6.2 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.7 MB 6.2 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 6.0 MB/s  0:00:02
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np


In [3]:

print(np.__version__)

2.5.3


In [4]:
A = np.array([10,20,30,40])

In [5]:
#indexing
A[2]

np.int64(30)

In [6]:
A[0]

np.int64(10)

In [7]:
#slicing
A[:2]

array([10, 20])

In [8]:
A[0] = 2#it is int
A

array([ 2, 20, 30, 40])

In [9]:
A[0] = 'pune'

ValueError: invalid literal for int() with base 10: 'pune'

In [10]:
A[0] = 'A'

ValueError: invalid literal for int() with base 10: 'A'

In [12]:
A[0] = 1.222
A

array([ 1, 20, 30, 40])

In [5]:
A[0] = True
A

array([ 1, 20, 30, 40])

In [13]:
#iterable
for i in A:
    print(i)

1
20
30
40


In [14]:
#funtions
A.sum()

np.int64(91)

In [15]:
A.min()

np.int64(1)

In [16]:
A.max()

np.int64(40)

In [17]:
#diffrent ways to create numpy array
A = np.array([12,20])

In [20]:
B = np.arange(10,20,2) #exclusive
B#start from 10 end at before 20 and increment by 2

array([10, 12, 14, 16, 18])

In [21]:
C = np.linspace(0,1,5)#inclusive
C #start at 0 and end at 1 and increment at 5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
C = np.linspace(0,10,3)
C

array([ 0.,  5., 10.])

In [25]:
C = np.linspace(3,15,5)
C #take starting and end at this and makes the parts at the last 5

array([ 3.,  6.,  9., 12., 15.])

In [6]:
A.std()

np.float64(14.411367041332339)

In [7]:
np.random.randint(0,100,10)

array([60, 72, 90, 41, 47, 60,  6, 97, 15, 18], dtype=int32)

In [8]:
np.random.seed(7)
np.random.randint(0,100,10)

array([47, 68, 25, 67, 83, 23, 92, 57, 14, 23], dtype=int32)

In [3]:
A = np.array([[10,20,30],[40,50,60]])

In [4]:
print(A)

[[10 20 30]
 [40 50 60]]


In [5]:
A

array([[10, 20, 30],
       [40, 50, 60]])

In [7]:
print(A[0][2])

30


In [8]:
A[-1][-1]

np.int64(60)

In [9]:
print(A[0,2])

30


### Properties 

In [10]:
A.dtype #tells the which type of data

dtype('int64')

In [11]:
print(A.dtype)

int64


In [12]:
A.ndim #tells the how much dimentions code

2

In [13]:
A.size #tells the number of element

6

In [14]:
A.shape #give value in tuple (row,column)

(2, 3)

##### Reshape 

In [15]:
A = np.array([10, 12, 14, 16, 18])

In [16]:
print(A.ndim)
print(A.size)
print(A.shape)

1
5
(5,)


In [17]:
B = A.reshape(3,2)
B

ValueError: cannot reshape array of size 5 into shape (3,2)

In [18]:
A = np.array([10, 12, 14, 16, 18,20])
print(A.ndim)
print(A.size)
print(A.shape)

1
6
(6,)


In [19]:
B = A.reshape(3,2)
B

array([[10, 12],
       [14, 16],
       [18, 20]])

In [21]:
print(B.ndim)
print(B.size)
print(B.shape)

2
6
(3, 2)


In [22]:
c = A.reshape(2,3)
c

array([[10, 12, 14],
       [16, 18, 20]])

In [23]:
d = A.reshape(6,1)
d

array([[10],
       [12],
       [14],
       [16],
       [18],
       [20]])

In [24]:
e = A.reshape(1,6)
e

array([[10, 12, 14, 16, 18, 20]])

In [25]:
np.random.seed(49)
marks = np.random.randint(0,100,(6,4))

In [26]:
marks

array([[42, 45, 40, 54],
       [12, 69,  5, 49],
       [18, 36, 12, 96],
       [82, 99, 26,  6],
       [59, 33, 70, 15],
       [92, 79, 72, 99]], dtype=int32)

In [28]:
#topper marks in every subject?
print(marks.max(axis = 0))

array([92, 99, 72, 99], dtype=int32)

In [31]:
#what is avg marks of topper?
print(marks.max(axis = 0).mean())

90.5


In [33]:
#addition of each row
print(marks.sum(axis = 1))

[181 135 162 213 177 342]


In [34]:
#avg marks of each subject
print(marks.mean(axis = 0))

[50.83333333 60.16666667 37.5        53.16666667]
