In [1]:
import numpy as np

In [2]:
names = np.array(["A", "B", "C", "D"])
marks = np.array([75, 95, 60, 85])
# Top student's name
# Top student's marks
# Lowest student's name
# Students sorted by marks
# Students who scored above 80

In [3]:
top = np.argmax(marks)#it returns the index of max elemnt
print(top)

1


In [5]:
print(names[top])
print(marks[top])

B
95


In [6]:
low = np.argmin(marks)#it returns the index of max elemnt
print(low)

2


In [7]:
print(names[low])
print(marks[low])

C
60


In [9]:
np.sort(marks)

array([60, 75, 85, 95])

In [11]:
np.argsort(marks) #sort by index

array([2, 0, 3, 1])

In [12]:
names[np.argsort(marks)]

array(['C', 'A', 'D', 'B'], dtype='<U1')

In [13]:
arr = np.array([10, 20, 30, 40, 50])
# Is any value greater than 45?
# Are all values greater than 5?
# Are all values greater than 20?

In [15]:
print(np.any(arr > 45))

True


In [16]:
np.all(arr > 5)

np.True_

In [17]:
np.all(arr > 20)

np.False_

In [18]:
data = np.array([10, 20, 30, 40, 50, 60, 70])

# 1. Find square root
# 2. Find square of every value
# 3. Find absolute values of [-10, 20, -30]
# 4. Round [2.345, 5.678] to 2 decimals
# 5. Find floor and ceil of [2.3, 5.8]
# 6. Find mean
# 7. Find median
# 8. Find variance
# 9. Find standard deviation
# 10. Find 25th and 75th percentile

In [35]:
print(np.sqrt(data))
print(np.pow(data,2))
print(np.abs([-10, 20, -30]))
print(np.round( [2.345, 5.678],2))
print(np.floor([2.3, 5.8]))
print(np.ceil([2.3, 5.8]))
print(np.mean(data))
print(np.var(data))
print(np.std(data))
print(np.percentile(data,25))
print(np.percentile(data,75))
print(np.percentile(data,50))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669
 8.36660027]
[ 100  400  900 1600 2500 3600 4900]
[10 20 30]
[2.35 5.68]
[2. 5.]
[3. 6.]
40.0
400.0
20.0
25.0
55.0
40.0


In [36]:

A = np.array([
    [2, 3],
    [4, 5]
])

B = np.array([
    [1, 2],
    [3, 4]
])

# 1. Add A and B
# 2. Subtract B from A
# 3. Multiply A and B element-wise
# 4. Perform matrix multiplication
# 5. Find transpose of A
# 6. Find determinant of A
# 7. Find inverse of A
# 8. Find dot product of [2,3] and [4,5]

In [46]:
print(A + B)
print(A - B)
print(A * B)
print(A @ B)
print(A.T)
print(np.linalg.det(A))
print(np.linalg.inv(A))
print(np.dot([2,3],[4,5]))

[[3 5]
 [7 9]]
[[1 1]
 [1 1]]
[[ 2  6]
 [12 20]]
[[11 16]
 [19 28]]
[[2 4]
 [3 5]]
-2.0
[[-2.5  1.5]
 [ 2.  -1. ]]
23
