# NumPy Complete Revision Notebook
## Lectures 36–43

This notebook covers the complete NumPy syllabus taught before Pandas.

### Topics
1. NumPy Basics
2. Indexing & Slicing
3. Array Creation
4. Array Operations & Axis
5. Array Manipulation
6. Searching & Sorting
7. Mathematical & Statistical Functions
8. Linear Algebra & Matrix Operations
9. Practice Examples
10. Challenging Questions

**Run each code cell and change the values to practice.**

## 1. Import NumPy

In [2]:
import numpy as np

print(np.__version__)

2.5.3


## 2. Creating NumPy Arrays

### Main function
`np.array()` converts Python lists/tuples into NumPy arrays.

In [3]:
arr = np.array([10, 20, 30, 40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


## 3. Array Dimensions and Properties

Important properties:
- `ndim` → number of dimensions
- `shape` → rows and columns / dimensions
- `size` → total number of elements
- `dtype` → data type

In [4]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([[10, 20, 30], [40, 50, 60]])

print("1D:", arr1)
print("ndim:", arr1.ndim)
print("shape:", arr1.shape)
print("size:", arr1.size)
print("dtype:", arr1.dtype)

print()
print("2D:", arr2)
print("ndim:", arr2.ndim)
print("shape:", arr2.shape)
print("size:", arr2.size)
print("dtype:", arr2.dtype)

1D: [10 20 30]
ndim: 1
shape: (3,)
size: 3
dtype: int64

2D: [[10 20 30]
 [40 50 60]]
ndim: 2
shape: (2, 3)
size: 6
dtype: int64


## 4. 1D, 2D and 3D Arrays

In [5]:
a1 = np.array([1, 2, 3])

a2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

a3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(a1)
print(a2)
print(a3)
print("Dimensions:", a1.ndim, a2.ndim, a3.ndim)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 1 2 3


## 5. Indexing

### 1D
`arr[index]`

### 2D
`arr[row, column]`

Python indexing starts from `0`.

In [6]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[-1])

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(data[0, 1])
print(data[2, 2])
print(data[1])

10
30
50
20
90
[40 50 60]


## 6. Slicing

Pattern:

`arr[start:stop:step]`

- start included
- stop excluded
- step controls the jump

In [7]:
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:5])
print(arr[:4])
print(arr[2:])
print(arr[::2])
print(arr[::-1])

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(data[0:2, 1:3])
print(data[:, 1])
print(data[1, :])

[20 30 40 50]
[10 20 30 40]
[30 40 50 60]
[10 30 50]
[60 50 40 30 20 10]
[[20 30]
 [50 60]]
[20 50 80]
[40 50 60]


## 7. Boolean Indexing / Filtering

In [8]:
marks = np.array([45, 60, 75, 30, 90, 55])

print(marks[marks > 50])
print(marks[marks >= 60])
print(marks[(marks > 40) & (marks < 80)])
print(marks[(marks < 40) | (marks > 80)])
print(marks[~(marks > 50)])

[60 75 90 55]
[60 75 90]
[45 60 75 55]
[30 90]
[45 30]


## 8. View vs Copy

- `view()` shares the original data.
- `copy()` creates independent data.

In [9]:
arr = np.array([10, 20, 30, 40])

view_arr = arr.view()
copy_arr = arr.copy()

view_arr[0] = 100
copy_arr[1] = 200

print("Original:", arr)
print("View:", view_arr)
print("Copy:", copy_arr)

Original: [100  20  30  40]
View: [100  20  30  40]
Copy: [ 10 200  30  40]


## 9. Special Array Creation Functions

- `zeros()`
- `ones()`
- `full()`
- `arange()`
- `linspace()`
- `eye()`

In [10]:
print(np.zeros(5))
print(np.zeros((2, 3)))

print(np.ones(4))
print(np.ones((2, 3)))

print(np.full(5, 7))
print(np.full((2, 3), 9))

print(np.arange(1, 10, 2))
print(np.linspace(0, 10, 5))

print(np.eye(3))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[7 7 7 7 7]
[[9 9 9]
 [9 9 9]]
[1 3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 10. Random Arrays

- `np.random.rand()` → random decimal values from 0 to 1
- `np.random.randint()` → random integers
- `np.random.seed()` → repeatable random results

In [11]:
np.random.seed(10)

print(np.random.rand(5))
print(np.random.rand(2, 3))
print(np.random.randint(1, 10, 5))
print(np.random.randint(1, 100, (3, 3)))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
[[0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982]]
[1 5 7 9 2]
[[73 79 50]
 [52 55 78]
 [70 14 26]]


## 11. Reshape, Flatten and Ravel

In [12]:
arr = np.arange(1, 7)

matrix = arr.reshape(2, 3)

print("Original:", arr)
print("Reshape:")
print(matrix)

print("Flatten:", matrix.flatten())
print("Ravel:", matrix.ravel())

print("Flatten with -1:", matrix.reshape(-1))

Original: [1 2 3 4 5 6]
Reshape:
[[1 2 3]
 [4 5 6]]
Flatten: [1 2 3 4 5 6]
Ravel: [1 2 3 4 5 6]
Flatten with -1: [1 2 3 4 5 6]


## 12. Element-wise Arithmetic

NumPy performs arithmetic element by element.

In [13]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

print(a + 5)
print(a * 2)

[12 24 35]
[ 8 16 25]
[ 20  80 150]
[5. 5. 6.]
[100 400 900]
[15 25 35]
[20 40 60]


## 13. Comparisons and Conditions

In [14]:
arr = np.array([10, 20, 30, 40, 50])

print(arr > 25)
print(arr == 30)
print(arr != 30)
print(arr[arr > 25])

[False False  True  True  True]
[False False  True False False]
[ True  True False  True  True]
[30 40 50]


## 14. Aggregation Functions

Important:
- `sum`
- `mean`
- `max`
- `min`
- `median`
- `std`
- `var`

In [15]:
arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Median:", np.median(arr))
print("Std:", np.std(arr))
print("Variance:", np.var(arr))

Sum: 150
Mean: 30.0
Max: 50
Min: 10
Median: 30.0
Std: 14.142135623730951
Variance: 200.0


## 15. Axis

For a 2D array:
- `axis=0` → down the rows → column-wise result
- `axis=1` → across columns → row-wise result

In [16]:
marks = np.array([
    [80, 70, 90],
    [60, 75, 85],
    [90, 85, 95]
])

print("Column sum:", np.sum(marks, axis=0))
print("Row sum:", np.sum(marks, axis=1))

print("Column mean:", np.mean(marks, axis=0))
print("Row mean:", np.mean(marks, axis=1))

print("Column max:", np.max(marks, axis=0))
print("Row min:", np.min(marks, axis=1))

Column sum: [230 230 270]
Row sum: [240 220 270]
Column mean: [76.66666667 76.66666667 90.        ]
Row mean: [80.         73.33333333 90.        ]
Column max: [90 85 95]
Row min: [70 60 85]


## 16. Broadcasting

A scalar operation is applied to every element.

In [17]:
marks = np.array([50, 60, 70, 80])

bonus = 5

print(marks + bonus)
print(marks - bonus)
print(marks * 2)

[55 65 75 85]
[45 55 65 75]
[100 120 140 160]


## 17. Concatenation

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.concatenate((a, b)))

[1 2 3 4 5 6]


## 18. Concatenation with 2D Arrays

In [19]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print("axis=0:")
print(np.concatenate((a, b), axis=0))

print("axis=1:")
print(np.concatenate((a, b), axis=1))

axis=0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
axis=1:
[[1 2 5 6]
 [3 4 7 8]]


## 19. vstack and hstack

In [20]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print("vstack:")
print(np.vstack((a, b)))

print("hstack:")
print(np.hstack((a, b)))

vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack:
[[1 2 5 6]
 [3 4 7 8]]


## 20. split and array_split

In [21]:
arr = np.arange(1, 9)

print(np.split(arr, 2))
print(np.array_split(arr, 3))

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


## 21. Transpose

In [22]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)
print(arr.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## 22. Mathematical Functions

- `sqrt`
- `power`
- `abs`
- `round`
- `floor`
- `ceil`

In [23]:
arr = np.array([-2.7, -1.2, 2.3, 4.8])

print("sqrt:", np.sqrt(np.array([4, 9, 16, 25])))
print("power:", np.power(np.array([2, 3, 4]), 2))
print("abs:", np.abs(arr))
print("round:", np.round(arr))
print("round 2:", np.round(arr, 2))
print("floor:", np.floor(arr))
print("ceil:", np.ceil(arr))

sqrt: [2. 3. 4. 5.]
power: [ 4  9 16]
abs: [2.7 1.2 2.3 4.8]
round: [-3. -1.  2.  5.]
round 2: [-2.7 -1.2  2.3  4.8]
floor: [-3. -2.  2.  4.]
ceil: [-2. -1.  3.  5.]


## 23. Logarithmic Functions

In [24]:
arr = np.array([1, 10, 100, 1000])

print("log:", np.log(arr))
print("log10:", np.log10(arr))

log: [0.         2.30258509 4.60517019 6.90775528]
log10: [0. 1. 2. 3.]


## 24. Trigonometric Functions

In [25]:
angles = np.array([0, np.pi / 2, np.pi])

print("sin:", np.sin(angles))
print("cos:", np.cos(angles))
print("tan:", np.tan(angles))

sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


## 25. Percentiles

In [26]:
marks = np.array([40, 50, 60, 70, 80, 90, 100])

print("25th:", np.percentile(marks, 25))
print("50th:", np.percentile(marks, 50))
print("75th:", np.percentile(marks, 75))

25th: 55.0
50th: 70.0
75th: 85.0


## 26. Unique Values and Counts

In [27]:
arr = np.array([10, 20, 20, 30, 30, 30, 40])

print("Unique:", np.unique(arr))

values, counts = np.unique(arr, return_counts=True)

print("Values:", values)
print("Counts:", counts)

Unique: [10 20 30 40]
Values: [10 20 30 40]
Counts: [1 2 3 1]


## 27. where()

### Two common forms

`np.where(condition)` → positions where condition is true

`np.where(condition, true_value, false_value)` → choose values based on condition

In [28]:
arr = np.array([10, 60, 30, 80, 40])

print(np.where(arr > 50))

result = np.where(arr >= 50, "Pass", "Fail")
print(result)

(array([1, 3]),)
['Fail' 'Pass' 'Fail' 'Pass' 'Fail']


## 28. Sorting

In [29]:
arr = np.array([50, 20, 80, 10, 40])

print("np.sort:", np.sort(arr))

arr2 = arr.copy()
arr2.sort()

print("arr.sort:", arr2)
print("Original:", arr)

np.sort: [10 20 40 50 80]
arr.sort: [10 20 40 50 80]
Original: [50 20 80 10 40]


## 29. argsort()

Returns the indexes that would sort the array.

In [30]:
marks = np.array([85, 60, 95, 75])
names = np.array(["Tejas", "Amit", "Rahul", "Sneha"])

index = np.argsort(marks)

print("Indexes:", index)
print("Sorted names:", names[index])
print("Sorted marks:", marks[index])

Indexes: [1 3 0 2]
Sorted names: ['Amit' 'Sneha' 'Tejas' 'Rahul']
Sorted marks: [60 75 85 95]


## 30. argmax and argmin

In [31]:
marks = np.array([85, 60, 95, 75])

print("Maximum value:", np.max(marks))
print("Maximum index:", np.argmax(marks))

print("Minimum value:", np.min(marks))
print("Minimum index:", np.argmin(marks))

Maximum value: 95
Maximum index: 2
Minimum value: 60
Minimum index: 1


## 31. nonzero(), any(), all()

In [32]:
arr = np.array([0, 5, 0, 10, 20])

print("Non-zero positions:", np.nonzero(arr))

marks = np.array([60, 70, 80])

print("Any > 75:", np.any(marks > 75))
print("All > 50:", np.all(marks > 50))
print("All > 75:", np.all(marks > 75))

Non-zero positions: (array([1, 3, 4]),)
Any > 75: True
All > 50: True
All > 75: False


## 32. Covariance and Correlation

In [33]:
hours = np.array([1, 2, 3, 4, 5])
marks = np.array([20, 40, 60, 80, 100])

print("Covariance:")
print(np.cov(hours, marks))

print("Correlation:")
print(np.corrcoef(hours, marks))

Covariance:
[[   2.5   50. ]
 [  50.  1000. ]]
Correlation:
[[1. 1.]
 [1. 1.]]


## 33. Linear Algebra

Important functions:
- `np.dot()`
- `np.matmul()`
- `@`
- `np.linalg.det()`
- `np.linalg.inv()`
- `np.linalg.solve()`
- `np.linalg.eig()`
- `np.linalg.norm()`

In [34]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Element-wise:")
print(A * B)

print("Matrix multiplication:")
print(A @ B)

print("matmul:")
print(np.matmul(A, B))

print("dot:")
print(np.dot(A, B))

print("Transpose:")
print(A.T)

print("Determinant:")
print(np.linalg.det(A))

print("Inverse:")
print(np.linalg.inv(A))

print("Norm:")
print(np.linalg.norm(np.array([3, 4])))

Element-wise:
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]
matmul:
[[19 22]
 [43 50]]
dot:
[[19 22]
 [43 50]]
Transpose:
[[1 3]
 [2 4]]
Determinant:
-2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Norm:
5.0


## 34. Solving Linear Equations

Example:

`2x + y = 5`

`x + y = 3`

In [35]:
A = np.array([
    [2, 1],
    [1, 1]
])

B = np.array([5, 3])

solution = np.linalg.solve(A, B)

print("x =", solution[0])
print("y =", solution[1])

x = 2.0
y = 1.0


## 35. Eigenvalues and Eigenvectors

In [36]:
A = np.array([
    [2, 0],
    [0, 3]
])

values, vectors = np.linalg.eig(A)

print("Eigenvalues:")
print(values)

print("Eigenvectors:")
print(vectors)

Eigenvalues:
[2.+0.j 3.+0.j]
Eigenvectors:
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


# Complete NumPy Function Reference

### Creation
- `np.array()`
- `np.zeros()`
- `np.ones()`
- `np.full()`
- `np.arange()`
- `np.linspace()`
- `np.eye()`
- `np.random.rand()`
- `np.random.randint()`
- `np.random.seed()`

### Properties
- `.ndim`
- `.shape`
- `.size`
- `.dtype`

### Selection
- indexing
- slicing
- Boolean indexing
- `np.where()`
- `np.nonzero()`

### Manipulation
- `.reshape()`
- `.flatten()`
- `.ravel()`
- `.T`
- `np.concatenate()`
- `np.vstack()`
- `np.hstack()`
- `np.split()`
- `np.array_split()`
- `.copy()`
- `.view()`

### Calculations
- `np.sum()`
- `np.mean()`
- `np.max()`
- `np.min()`
- `np.median()`
- `np.std()`
- `np.var()`
- `np.percentile()`
- `np.cov()`
- `np.corrcoef()`

### Mathematical
- `np.sqrt()`
- `np.power()`
- `np.abs()`
- `np.round()`
- `np.floor()`
- `np.ceil()`
- `np.log()`
- `np.log10()`
- `np.sin()`
- `np.cos()`
- `np.tan()`

### Searching / Sorting
- `np.unique()`
- `np.sort()`
- `.sort()`
- `np.argsort()`
- `np.argmax()`
- `np.argmin()`
- `np.any()`
- `np.all()`

### Linear Algebra
- `np.dot()`
- `np.matmul()`
- `@`
- `np.linalg.det()`
- `np.linalg.inv()`
- `np.linalg.solve()`
- `np.linalg.eig()`
- `np.linalg.norm()`

# 🧪 Practice Section — One Line → Code

For each question, first read the one-line requirement and then write the code yourself.

## Basic Practice

### Practice 1
**One line:** Create a NumPy array containing numbers from 10 to 50 with a step of 10.

Try it yourself first.

In [37]:
# Your solution
arr = np.arange(10, 51, 10)
print(arr)

[10 20 30 40 50]


### Practice 2
**One line:** Create a 3×4 matrix filled with zeros.

Try it yourself first.

In [38]:
# Your solution
arr = np.zeros((3, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Practice 3
**One line:** Create five equally spaced values between 0 and 100.

Try it yourself first.

In [39]:
# Your solution
arr = np.linspace(0, 100, 5)
print(arr)

[  0.  25.  50.  75. 100.]


### Practice 4
**One line:** Find the shape, size, dimensions, and data type of a 2D array.

Try it yourself first.

In [40]:
# Your solution
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


### Practice 5
**One line:** Extract the second row from a 3×3 matrix.

Try it yourself first.

In [41]:
# Your solution
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1])

[4 5 6]


### Practice 6
**One line:** Extract the last column from a 3×3 matrix.

Try it yourself first.

In [42]:
# Your solution
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[:, -1])

[3 6 9]


### Practice 7
**One line:** Select all marks greater than or equal to 60.

Try it yourself first.

In [43]:
# Your solution
marks = np.array([45, 60, 72, 55, 90, 38])
print(marks[marks >= 60])

[60 72 90]


### Practice 8
**One line:** Calculate the row-wise total of a marks matrix.

Try it yourself first.

In [44]:
# Your solution
marks = np.array([[80,70,90],[60,75,85],[90,85,95]])
print(np.sum(marks, axis=1))

[240 220 270]


### Practice 9
**One line:** Calculate the column-wise average of a marks matrix.

Try it yourself first.

In [45]:
# Your solution
marks = np.array([[80,70,90],[60,75,85],[90,85,95]])
print(np.mean(marks, axis=0))

[76.66666667 76.66666667 90.        ]


### Practice 10
**One line:** Add a bonus of 5 marks to every student.

Try it yourself first.

In [46]:
# Your solution
marks = np.array([55, 65, 75, 85])
print(marks + 5)

[60 70 80 90]


### Practice 11
**One line:** Convert a 1D array of 12 values into a 3×4 matrix.

Try it yourself first.

In [47]:
# Your solution
arr = np.arange(1, 13)
print(arr.reshape(3, 4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Practice 12
**One line:** Reverse an array without changing the original array.

Try it yourself first.

In [48]:
# Your solution
arr = np.array([10,20,30,40,50])
print(arr[::-1])
print(arr)

[50 40 30 20 10]
[10 20 30 40 50]


### Practice 13
**One line:** Find unique values and their frequencies.

Try it yourself first.

In [49]:
# Your solution
arr = np.array([10,20,20,30,30,30,40])
values, counts = np.unique(arr, return_counts=True)
print(values)
print(counts)

[10 20 30 40]
[1 2 3 1]


### Practice 14
**One line:** Find the index of the student with the highest marks.

Try it yourself first.

In [50]:
# Your solution
marks = np.array([72, 88, 95, 67])
print(np.argmax(marks))

2


### Practice 15
**One line:** Sort student names according to their marks.

Try it yourself first.

In [51]:
# Your solution
names = np.array(["Tejas","Amit","Rahul","Sneha"])
marks = np.array([85,60,95,75])
idx = np.argsort(marks)
print(names[idx])
print(marks[idx])

['Amit' 'Sneha' 'Tejas' 'Rahul']
[60 75 85 95]


### Practice 16
**One line:** Replace values below 50 with the word 'Fail' and others with 'Pass'.

Try it yourself first.

In [52]:
# Your solution
marks = np.array([35, 55, 42, 70, 80])
result = np.where(marks < 50, "Fail", "Pass")
print(result)

['Fail' 'Pass' 'Fail' 'Pass' 'Pass']


### Practice 17
**One line:** Find the 25th, 50th, and 75th percentiles of a dataset.

Try it yourself first.

In [53]:
# Your solution
data = np.array([10,20,30,40,50,60,70,80,90])
print(np.percentile(data, 25))
print(np.percentile(data, 50))
print(np.percentile(data, 75))

30.0
50.0
70.0


### Practice 18
**One line:** Calculate the standard deviation and variance of a dataset.

Try it yourself first.

In [54]:
# Your solution
data = np.array([10,20,30,40,50])
print(np.std(data))
print(np.var(data))

14.142135623730951
200.0


### Practice 19
**One line:** Calculate the dot product of two vectors.

Try it yourself first.

In [55]:
# Your solution
a = np.array([2,3,4])
b = np.array([5,6,7])
print(np.dot(a, b))

56


### Practice 20
**One line:** Multiply two matrices using the @ operator.

Try it yourself first.

In [56]:
# Your solution
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A @ B)

[[19 22]
 [43 50]]


# 🔥 Challenging NumPy Questions

These are closer to Data Science / interview-style problems.

## Challenge 1 — Student Analysis
Given marks of 10 students:
- Find average marks
- Find highest and lowest marks
- Find the index of the topper
- Find students scoring above average
- Find the 25th and 75th percentile
- Find standard deviation

In [57]:
marks = np.array([65, 78, 92, 55, 88, 71, 95, 43, 82, 69])
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.argmax(marks))
above = np.mean(marks)
print(marks[marks > above])
print(np.percentile(marks,25))
print(np.percentile(marks,75))
print(np.std(marks))

73.8
95
43
6
[78 92 88 95 82]
66.0
86.5
15.7403938959608


## Challenge 2 — Top 3 Students
Given names and marks, find the top 3 students while keeping names and marks correctly matched.

In [58]:
names = np.array(["Amit", "Tejas", "Rahul", "Sneha", "Priya", "Rohan"])
marks = np.array([72, 95, 81, 88, 67, 91])
A = np.argsort(marks)
B = A[::-1]
C = B[:3]
for i in C:
    print(names[i])

Tejas
Rohan
Sneha


## Challenge 3 — Replace Invalid Marks
Marks are between 0 and 100. Replace invalid marks with 0.

Example:
`[80, 105, 70, -5, 90]`

Expected:
`[80, 0, 70, 0, 90]`

In [83]:
marks = np.array([80, 105, 70, -5, 90])


# marks = [1,2,0,-2,1055]
# for i in range(len(marks)):
#     if (marks[i] < 0 or marks[i] > 100):
#         marks[i] = 0
# print(marks)
    
#another way
marks[(marks > 100) | (marks < 0)] = 0
print(marks)

    


[80  0 70  0 90]


## Challenge 4 — Normalized Data
Given:
`[10, 20, 30, 40, 50]`

Convert each value into a value between 0 and 1 using:

`(x - min) / (max - min)`

In [95]:
data = np.array([10, 20, 30, 40, 50])
min_val = np.min(data)
max_val = np.max(data)

if max_val != min_val:
    data = (data - min_val) / (max_val - min_val)

else:
    N_data = np.zeros_like(data)
    

# data[(data - min_val) / (max_val - min_val)]
print(data)

    


# Write your solution here


[0.   0.25 0.5  0.75 1.  ]


## Challenge 5 — Find Outliers Using IQR
Given a dataset:
`[10, 12, 11, 13, 15, 14, 12, 100]`

1. Find Q1.
2. Find Q3.
3. Calculate IQR = Q3 - Q1.
4. Calculate lower bound = Q1 - 1.5 × IQR.
5. Calculate upper bound = Q3 + 1.5 × IQR.
6. Find values outside these bounds.

In [107]:
data = np.array([10, 12, 11, 13, 15, 14, 12, 100])
sorted_data = data.sort()
print(data)
Q1 = data[:5].mean()
Q3 = data[5:].mean()
IQR = Q3 - Q1
low = Q1 - (1.5 * IQR)
high = Q3 + (1.5 * IQR)
print(low)
print(high)

print(data[(data > high) | (data < low)])



[ 10  11  12  12  13  14  15 100]
-35.49999999999999
90.1
[100]


## Challenge 6 — Sales Analysis
Each row represents a month and each column represents a product.

Find:
- Total sales of each product
- Total sales of each month
- Best-selling product
- Best month
- Overall average sales

In [111]:
sales = np.array([
    [100, 150, 120],
    [130, 170, 140],
    [160, 180, 150],
    [120, 160, 130]
])

print(np.sum(sales,axis = 0))
print(np.sum(sales,axis = 1))
print(np.sum(sales,axis = 0).max())
print(np.sum(sales,axis = 1).max())
print(np.sum(sales,axis = 1).mean())



[510 660 540]
[370 440 490 410]
660
490
427.5


## Challenge 7 — Students Above Average
Find all students whose marks are greater than the class average and print their names and marks.

In [115]:
names = np.array(["Amit", "Tejas", "Rahul", "Sneha", "Priya"])
marks = np.array([55, 90, 72, 45, 82])
a1 = marks[marks > np.mean(marks)]
for i in range (len(marks)):
    if marks[i] in a1:
        print(names[i],marks[i])

Tejas 90
Rahul 72
Priya 82


## Challenge 8 — Matrix Multiplication
Given two matrices, check their shapes and perform matrix multiplication only when multiplication is possible.

In [123]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

a = A.shape #it is tuple so we can acces it by the a[1] and b[0] it it same multiply
b = B.shape
if a[1] == b[0]:
    print(A @ B)
else:
    print("Multiplication is not possible")

# Write your solution here



[[220 280]
 [490 640]]


## Challenge 9 — Feature and Weight Calculation
This is a simple Machine Learning-style calculation.

Each row contains features. Calculate prediction using:

`prediction = features @ weights`

In [129]:
features = np.array([
    [2, 3, 1],
    [4, 2, 3],
    [5, 1, 4],
    [3, 6, 2]
])

weights = np.array([10, 5, 2])
print(features @ weights)

# Write your solution here


[37 56 63 64]


## Challenge 10 — Complete Mini EDA with NumPy

Given the following sales data:
- Find total sales
- Find average sales
- Find maximum and minimum
- Find standard deviation
- Find top 3 sales
- Find values above average
- Find 25th and 75th percentiles
- Find unique sales values and their counts

In [153]:
sales = np.array([
    1200, 1500, 1200, 1800, 2100,
    1750, 1500, 2300, 900, 1600,
    1950, 2200, 1500, 1250, 2050
])
print(np.sum(sales))
print(np.mean(sales))
print(np.max(sales))
print(np.min(sales))
print(np.std(sales))
a = np.sort(sales)[-3:]
print(a)
print(sales[sales > np.mean(sales)])
print(np.percentile(sales,25))
print(np.percentile(sales,75))
print(np.unique(sales))
print(np.unique(sales,return_counts = True))

# Write your solution here


24800
1653.3333333333333
2300
900
400.6106450019631
[2100 2200 2300]
[1800 2100 1750 2300 1950 2200 2050]
1375.0
2000.0
[ 900 1200 1250 1500 1600 1750 1800 1950 2050 2100 2200 2300]
(array([ 900, 1200, 1250, 1500, 1600, 1750, 1800, 1950, 2050, 2100, 2200,
       2300]), array([1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1]))


# ✅ NumPy Final Revision Checklist

Before starting Pandas, you should be comfortable with:

- [ ] `np.array()`
- [ ] `ndim`, `shape`, `size`, `dtype`
- [ ] Indexing
- [ ] Slicing
- [ ] Boolean filtering
- [ ] `copy()` vs `view()`
- [ ] `zeros()`, `ones()`, `full()`
- [ ] `arange()`, `linspace()`, `eye()`
- [ ] Random arrays
- [ ] `reshape()`, `flatten()`, `ravel()`
- [ ] Element-wise operations
- [ ] Broadcasting
- [ ] `axis=0` and `axis=1`
- [ ] `concatenate()`
- [ ] `vstack()` and `hstack()`
- [ ] `split()` and `array_split()`
- [ ] Transpose
- [ ] Mathematical functions
- [ ] Percentiles
- [ ] Variance and standard deviation
- [ ] Covariance and correlation
- [ ] `where()`
- [ ] `unique()`
- [ ] `sort()` and `argsort()`
- [ ] `argmax()` and `argmin()`
- [ ] `any()` and `all()`
- [ ] `nonzero()`
- [ ] Dot product
- [ ] Matrix multiplication
- [ ] Determinant
- [ ] Inverse
- [ ] Solving equations
- [ ] Basic eigenvalues/eigenvectors
- [ ] Norm

## Next
### Lecture 44 — Pandas Introduction
We will start Pandas with:
`Series → DataFrame → rows/columns → indexing → selecting data → basic dataset operations → CSV datasets`.
